//
//  ColorPickerWorker.swift
//  
//
//  Created by Dominik Kapusta on 14/10/2017.
//  Copyright (c) 2017 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SwiftSocket

func synchronized<T>(_ lock: AnyObject, _ body: () throws -> T) rethrows -> T {
    objc_sync_enter(lock)
    defer { objc_sync_exit(lock) }
    return try body()
}

extension UIColor {
    var hexData: Data {
        var r: CGFloat = 0
        var g: CGFloat = 0
        var b: CGFloat = 0
        var a: CGFloat = 0
        
        self.getRed(&r, green: &g, blue: &b, alpha: &a)
        
        r = max(0, min(1, r))
        g = max(0, min(1, g))
        b = max(0, min(1, b))

        var data = Data()
        data.append(UInt8(r * 0xff))
        data.append(UInt8(g * 0xff))
        data.append(UInt8(b * 0xff))
        return data
    }
}

class ColorPickerWorker: NSObject, URLSessionDelegate
{
    private var socket: TCPClient? = nil
    
    private let instanceMutex = PThreadMutex(type: .recursive)
    private var _isTaskInProgress: Bool = false
    var isTaskInProgress: Bool {
        get {
            var value: Bool = false
            instanceMutex.sync {
                value = _isTaskInProgress
            }
            return value
        }
        set {
            instanceMutex.sync {
                _isTaskInProgress = newValue
            }
        }
    }

    private func queryString(with color: UIColor) -> String {
        var r: CGFloat = 0, g: CGFloat = 0, b: CGFloat = 0
        color.getRed(&r, green: &g, blue: &b, alpha: nil)
        
        let redString = String(Int(r*255))
            .addingPercentEncoding(withAllowedCharacters: .alphanumerics)!
        let greenString = String(Int(g*255))
            .addingPercentEncoding(withAllowedCharacters: .alphanumerics)!
        let blueString = String(Int(b*255))
            .addingPercentEncoding(withAllowedCharacters: .alphanumerics)!

        return "?r=\(redString)&g=\(greenString)&b=\(blueString)"
        
    }
    
    func getColor(_ completionHandler: @escaping ([String:Int]) -> Void) {

        if !isTaskInProgress {
            let url = URL(string: "https://zero.local/get_color")!
            let task = urlSession.dataTask(with: url) { (data: Data?, response: URLResponse?, error: Error?) in
                if let error = error {
                    print(error)
                    DispatchQueue.main.async {
                        completionHandler([:])
                    }
                } else if let data = data {
                    do {
                        let json = try JSONSerialization.jsonObject(with: data, options: [])
                        DispatchQueue.main.async {
                            completionHandler(json as? [String:Int] ?? [:])
                        }
                    } catch (let error) {
                        print("JSON deserialization error: \(error)")
                        DispatchQueue.main.async {
                            completionHandler([:])
                        }
                    }
                }
                self.isTaskInProgress = false
            }
            task.resume()
            isTaskInProgress = true
        }
    }
    
    func setColor(_ color: UIColor) {
        
//        if !isTaskInProgress {
//            let query = queryString(with: color)
//
//            let url = URL(string: "https://zero.local/color\(query)")!
//            let task = urlSession.dataTask(with: url) { (data: Data?, response: URLResponse?, error: Error?) in
//                if let error = error {
//                    print(error)
//                }
//                self.isTaskInProgress = false
//            }
//            task.resume()
//            isTaskInProgress = true
//
//        }

//        synchronized(self) { () -> Void in
        
            if socket == nil {
                socket = TCPClient(address: "192.168.1.101", port: 4000)
                switch socket!.connect(timeout: 30) {
                case .success:
                    break
                    
                case .failure(let error):
                    NSLog("failed to connect: \(error)")
                }
            }
            
            _ = socket?.send(data: color.hexData)
            socket?.close()
            socket = nil
//        }
    }
    
    private lazy var urlSession: URLSession = {
        let configuration = URLSessionConfiguration.default
        return URLSession(configuration: configuration,
                          delegate: self,
                          delegateQueue: workerQueue)
    }()
    
    private let workerQueue = OperationQueue()
    
    func urlSession(_ session: URLSession,
                    didReceive challenge: URLAuthenticationChallenge,
                    completionHandler: @escaping (URLSession.AuthChallengeDisposition, URLCredential?) -> Void)
    {
        if challenge.protectionSpace.authenticationMethod == NSURLAuthenticationMethodServerTrust {
            if challenge.protectionSpace.host == "zero.local" {
                
                if let certFile = Bundle.main.path(forResource: "cert", ofType: "der"),
                    let data = try? Data(contentsOf: URL(fileURLWithPath: certFile)),
                    let cert = SecCertificateCreateWithData(nil, data as CFData),
                    let trust = challenge.protectionSpace.serverTrust
                {
                    SecTrustSetAnchorCertificates(trust, [cert] as CFArray)
                    completionHandler(.useCredential, URLCredential(trust: trust))
                } else {
                    completionHandler(.cancelAuthenticationChallenge, nil)
                }
            } else {
                completionHandler(.performDefaultHandling, nil)
            }
        }
    }

}
