//
//  ColorPickerViewController.swift
//  
//
//  Created by Dominik Kapusta on 14/10/2017.
//  Copyright (c) 2017 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Color_Picker_for_iOS

protocol ColorPickerDisplayLogic: class
{
    func displaySomething(viewModel: ColorPicker.Something.ViewModel)
}

class ColorPickerViewController: UIViewController, ColorPickerDisplayLogic
{
    @IBOutlet private weak var colorPickerView: HRColorPickerView!

    var interactor: ColorPickerBusinessLogic?
    var router: (NSObjectProtocol & ColorPickerRoutingLogic & ColorPickerDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = ColorPickerInteractor()
        let presenter = ColorPickerPresenter()
        let router = ColorPickerRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        doSomething()
        colorPickerView.color = .red
        colorPickerView.addTarget(self,
                                  action: #selector(colorPickerDidChange(_:)),
                                  for: .valueChanged)
    }
    
    @objc private func colorPickerDidChange(_ colorPicker: HRColorPickerView) {
        if let color = colorPicker.color {
            interactor?.updateColor(request: ColorPicker.UpdateColor.Request(color: color))
        }
    }
    
    // MARK: Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func doSomething()
    {
        let request = ColorPicker.Something.Request()
        interactor?.doSomething(request: request)
    }
    
    func displaySomething(viewModel: ColorPicker.Something.ViewModel)
    {
        //nameTextField.text = viewModel.name
    }
}
