//
//  ColorPickerPresenter.swift
//  
//
//  Created by Dominik Kapusta on 14/10/2017.
//  Copyright (c) 2017 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ColorPickerPresentationLogic
{
    func presentSomething(response: ColorPicker.Something.Response)
}

class ColorPickerPresenter: ColorPickerPresentationLogic
{
    weak var viewController: ColorPickerDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: ColorPicker.Something.Response)
    {
        let viewModel = ColorPicker.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
