//
//  ColorPickerPresenter.swift
//  
//
//  Created by Dominik Kapusta on 14/10/2017.
//  Copyright (c) 2017 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ColorPickerPresentationLogic
{
    func computeCurrentState(response: ColorPicker.CurrentState.Response)
}

class ColorPickerPresenter: ColorPickerPresentationLogic
{
    weak var viewController: ColorPickerDisplayLogic?
    
    // MARK: Do something
    
    func computeCurrentState(response: ColorPicker.CurrentState.Response) {
        let color = UIColor(red: CGFloat(response.red)/255,
                            green: CGFloat(response.green)/255,
                            blue: CGFloat(response.blue)/255,
                            alpha: 1)
        let viewModel = ColorPicker.CurrentState.ViewModel(color: color, isMotionSensorEnabled: response.isMotionSensorEnabled, errorString: nil)

        viewController?.displayCurrentState(viewModel: viewModel)
    }
}
