//
//  ColorPickerModels.swift
//  
//
//  Created by Dominik Kapusta on 14/10/2017.
//  Copyright (c) 2017 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ColorPicker
{
    struct LEDState {
        let color: UIColor
        let motionSensor: MotionSensor
        
        struct MotionSensor {
            let isEnabled: Bool
            let isScheduleEnabled: Bool
            let scheduledStart: DateComponents?
            let scheduledEnd: DateComponents?
        }
        
        static let uninitialized = LEDState(color: .black,
                                            motionSensor: MotionSensor(isEnabled: false,
                                                                       isScheduleEnabled: false,
                                                                       scheduledStart: nil,
                                                                       scheduledEnd: nil))
    }
    
    // MARK: Use cases
    
    enum Something
    {
        struct Request
        {
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
    
    enum UpdateColor
    {
        struct Request
        {
            let color: UIColor
        }

        struct Response
        {
            let error: Error?
        }

        struct ViewModel
        {
            let errorString: String?
        }
    }
    
    enum UpdateMotionSensorState
    {
        struct Request
        {
            let isEnabled: Bool
        }
        
        struct Response
        {
            let error: Error?
        }
        
        struct ViewModel
        {
            let errorString: String?
        }
    }

    enum CurrentState
    {
        struct Request
        {
        }
        
        struct Response
        {
            let red: UInt8
            let green: UInt8
            let blue: UInt8
            let isMotionSensorEnabled: Bool
        }
        
        struct ViewModel
        {
            let color: UIColor
            let isMotionSensorEnabled: Bool
            let errorString: String?
        }
    }
}
