//
//  ColorPickerPresenter.swift
//  
//
//  Created by Dominik Kapusta on 14/10/2017.
//  Copyright (c) 2017 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ColorPickerPresentationLogic
{
    func computeCurrentColor(response: ColorPicker.CurrentColor.Response)
}

class ColorPickerPresenter: ColorPickerPresentationLogic
{
    weak var viewController: ColorPickerDisplayLogic?
    
    // MARK: Do something
    
    func computeCurrentColor(response: ColorPicker.CurrentColor.Response) {
        let color = UIColor(red: CGFloat(response.colorJSON["red"] ?? 0)/255,
                            green: CGFloat(response.colorJSON["green"] ?? 0)/255,
                            blue: CGFloat(response.colorJSON["blue"] ?? 0)/255,
                            alpha: 1)
        let viewModel = ColorPicker.CurrentColor.ViewModel(color: color, errorString: nil)

        viewController?.displayCurrentColor(viewModel: viewModel)
    }
}
