//
//  ColorPickerViewController.swift
//  
//
//  Created by Dominik Kapusta on 14/10/2017.
//  Copyright (c) 2017 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Color_Picker_for_iOS

protocol ColorPickerDisplayLogic: class
{
    func displayCurrentState(viewModel: ColorPicker.CurrentState.ViewModel)
}

class ColorPickerViewController: UIViewController, ColorPickerDisplayLogic
{
    @IBOutlet private weak var colorPickerView: HRColorPickerView!
    @IBOutlet private weak var motionSensorSwitch: UISwitch!

    var interactor: ColorPickerBusinessLogic?
    var router: (NSObjectProtocol & ColorPickerRoutingLogic & ColorPickerDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = ColorPickerInteractor()
        let presenter = ColorPickerPresenter()
        let router = ColorPickerRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        fetchCurrentState()
    }
    
    @IBAction private func colorPickerDidChange(_ colorPicker: HRColorPickerView) {
        if let color = colorPicker.color {
            interactor?.updateColor(request: ColorPicker.UpdateColor.Request(color: color))
        }
    }

    @IBAction private func motionSensorSwitchDidChange(_ sender: UISwitch) {
        interactor?.updateMotionSensorState(request:
            ColorPicker.UpdateMotionSensorState.Request(isEnabled: sender.isOn))
    }

    // MARK: Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func fetchCurrentState() {
        let request = ColorPicker.CurrentState.Request()
        interactor?.fetchCurrentState(request: request)
        colorPickerView.addTarget(self,
                                  action: #selector(colorPickerDidChange(_:)),
                                  for: .valueChanged)
    }
    
    func displayCurrentState(viewModel: ColorPicker.CurrentState.ViewModel) {
        colorPickerView.color = viewModel.color
        motionSensorSwitch.isOn = viewModel.isMotionSensorEnabled
    }

    // MARK -

    @IBAction func didCancelSchedule(_ segue: UIStoryboardSegue) {
//        periodPicker.selectedPeriod = period
    }

    @IBAction func didAdjustSchedule(_ segue: UIStoryboardSegue) {
        if let scheduleVC = segue.source as? ScheduleViewController {
//            period = .custom(startDate: customPeriodVC.startDate,
//                             endDate: customPeriodVC.endDate)
        }
    }

}
